### ISSUE TITLE
Auto-complete does not function with new sub-block syntax

### ISSUE THREAD

**Issue by joshuahansel** [dschwen/autocomplete-moose#12]
In MOOSE, sub-blocks no longer need the leading `./` or the terminating `../`. For instance,
```
[AuxVariables]
  [./a]
    (stuff)
  [../]
[]
```
can now just be
```
[AuxVariables]
  [a]
    (stuff)
  []
[]
```
However, it seems that when using the new syntax, the auto-complete functionality does not work - it seems to be triggered by `./` in the sub-block.

**Comment by dschwen** [comment]
Hm, yeah.. I guess a `[]` does not immediately jump back to the top level syntax. I guess I'll have to do a major revision of that plugin (using the JSON dump as well).

**Comment by tophmatthews** [comment]
This was what I was coming here to add, the new sub-block syntax without `./` and `../` isn't recognized still

**Comment by tophmatthews** [comment]
ping-a-ling @dschwen ...I see that the ../ syntax is quickly disappearing...

**Comment by tophmatthews** [comment]
since you mentioned you were stuck in meetings....ping @dschwen

**Comment by gardnerru** [comment]
Industry is also interested in this ;)

**Comment by dschwen** [comment]
Hey, all. The master branch of the plugin has support for this now. I'd love to get some testing before I publish a new version. Any volunteers?

You have to 
* uninstall the plugin in atom
* clone this repo
* make sure you deactivate _all_ conda environments (including base), run `conda deactivate` **twice**
* verify that `python` gives you python 2.X
* go into the repo directory
* run `apm link`
* run `apm install` (make sure you get the green checkmark)
* restart atom

**Comment by joshuahansel** [comment]
I just tried this, and it works for me 👍 I'll let you know if I encounter any issues.

**Comment by joshuahansel** [comment]
I don't know if this is related, but all of the sudden I'm getting this error when I start typing:
```
Error: Parser is in use
    at Parser.parseTextBuffer (/Users/hansje/atom_packages/autocomplete-moose/node_modules/tree-sitter/index.js:292:19)
    at Object.prepareCompletion (/Users/hansje/atom_packages/autocomplete-moose/lib/provider.coffee:106:12)
    at Object.getSuggestions (/Users/hansje/atom_packages/autocomplete-moose/lib/provider.coffee:89:10)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:648632
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:648148)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:647886)
    at AutocompleteManager.requestNewSuggestions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:656419)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:657510)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1201250)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1202691)
    at TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:504811)
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:492966)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16150
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39484)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39038)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16113)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:15662)
    at TextEditor.e.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:258508)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:94346)
```
I haven't figured out exactly what triggers this.

**Comment by tophmatthews** [comment]
Yeah, I get the same error @dschwen 
```
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-sitter/index.js:292
Hide Stack Trace
Error: Parser is in use
    at Parser.parseTextBuffer (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-sitter/index.js:292:19)
    at Object.prepareCompletion (/Users/topher/projects/autocomplete-moose/lib/provider.coffee:106:12)
    at Object.getSuggestions (/Users/topher/projects/autocomplete-moose/lib/provider.coffee:89:10)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:648632
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:648148)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:647886)
    at AutocompleteManager.requestNewSuggestions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:656419)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:657510)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1201250)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1202691)
    at TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:504811)
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:492966)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16150
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39529)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39038)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16113)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:15662)
    at TextEditor.e.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:258508)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:94346)
```
But it keeps working normally with and without the [./] [../] after the error is thrown?

**Comment by dschwen** [comment]
Ah, ok, I think I know what's going on...

**Comment by dschwen** [comment]
Ok, I believe ed5cd5f9e4e45ffb840723568925a07909df3b33 fixes this bug. I went ahead and released `v1.0.0` of the plugin. If you were testing the repo version you should run `apm unlink` and reinstall it from Atom.

I'm closing this issue. Pleas open a new issue if you discover more bugs with the plugin :-)

**Comment by gardnerru** [comment]
@dschwen I was not testing the repo but I get this when trying to update: 

Installing “autocomplete-moose@1.0.0” failed.Hide output…

> tree-sitter@0.16.1 install /private/var/folders/94/bf81fc610bxfpdn6yc7hxg880000gq/T/apm-install-dir-202054-3446-sir5a8.l2ce/node_modules/autocomplete-moose/node_modules/tree-sitter
> prebuild-install || node-gyp rebuild


> tree-sitter-hit@0.2.2 install /private/var/folders/94/bf81fc610bxfpdn6yc7hxg880000gq/T/apm-install-dir-202054-3446-sir5a8.l2ce/node_modules/autocomplete-moose/node_modules/tree-sitter-hit
> node-gyp rebuild


gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:282:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:596:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/94/bf81fc610bxfpdn6yc7hxg880000gq/T/apm-install-dir-202054-3446-sir5a8.l2ce/node_modules/autocomplete-moose/node_modules/tree-sitter-hit
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/94/bf81fc610bxfpdn6yc7hxg880000gq/T/apm-install-dir-202054-3446-sir5a8.l2ce/package.json'
npm WARN apm-install-dir-202054-3446-sir5a8.l2ce No description
npm WARN apm-install-dir-202054-3446-sir5a8.l2ce No repository field.
npm WARN apm-install-dir-202054-3446-sir5a8.l2ce No README data
npm WARN apm-install-dir-202054-3446-sir5a8.l2ce No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-hit@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-hit@0.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/russellgardner/.atom/.apm/_logs/2020-06-04T19_11_37_939Z

I tried the 'ol uninstall/reinstall with the same results. Any idea? Would you like the actual log?

**Comment by joshuahansel** [comment]
@gardnerru I had that as well. I created and activated a conda environment with python 2.7 and then tried installing again. I think the package should continue to work when deactivating the conda environment.
