### ISSUE TITLE
"Uncaught Callback must be a function"

### ISSUE THREAD

**Issue by cticenhour** [dschwen/autocomplete-moose#14]
Updated to Atom 1.39.1 yesterday (Mojave 10.14.6) and received an error - "Uncaught Callback must be a function" at `fs.js:157`. Triggered as I was editing an input file and the package was rebuilding MOOSE syntax data from a new app build. See the stack trace below:

```
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1290:14)
    at /Users/icenct/.atom/packages/autocomplete-moose/node_modules/fs-plus/lib/fs-plus.js:296:21
    at /Users/icenct/.atom/packages/autocomplete-moose/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:183:5)
```

Let me know if you need any more info!

**Comment by cticenhour** [comment]
Actually here is the error report produced by Atom as well: 

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [autocomplete-moose](https://github.com/dschwen/autocomplete-moose) package 0.23.1


### Stack Trace

Uncaught Callback must be a function

```
At fs.js:157

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1290:14)
    at /packages/autocomplete-moose/node_modules/fs-plus/lib/fs-plus.js:296:21
    at /packages/autocomplete-moose/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:183:5)
```

### Commands

```
     -8:59.2.0 editor:newline (input.hidden-input)
  2x -8:38.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
autocomplete-clang 0.12.0 
autocomplete-moose 0.23.1 
busy-signal 2.0.1 
clang-format 2.0.8 
language-latex 1.2.0 
language-moose 1.2.0 
latex 0.50.2 
make-runner 1.1.15 
pdf-view 0.71.0 
switch-header-source 0.34.1 
```

**Comment by dschwen** [comment]
`autocomplete-moose@v0.23.2` fixes this.

**Comment by cticenhour** [comment]
Thanks!
