### ISSUE TITLE
Failed to build syntax + Failed to activate autocomplete-moose

### ISSUE THREAD

**Issue by marinasessim** [dschwen/autocomplete-moose#16]
Hello, I was hitting the "Failed to build syntax" error first. The MOOSE executable was a couple of directories above my input files and I also tried to set the path. Uninstalled and installed a fresh version of atom, then re-added the moose packages. I still have MOOSE on Mojave, with the latest environment package for this OS.  I don't recall doing anything in particular that could have stopped the autocomplete. Please let me know if there is any other info that will help. Thanks!

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [autocomplete-moose](ssh://git@github.com/dschwen/autocomplete-moose) package 0.23.3

### Stack Trace

Failed to activate the autocomplete-moose package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1216532)
    at CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1217500)
    at Object.consumeProvider (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:162456)
    at Object.consumeProvider_2 (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:162154)
    at Provider.provide (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1121885)
    at ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3209660)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3217946)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3214922)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3214246)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3211856)
    at activationPromise.activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3214106)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3214049)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382452)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:941081
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:935687)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1124792)
    at e.bufferStream (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1124880)
    at Socket.e.on (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1123548)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12)
```

### Commands

```
     -3:34.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:24.3.0 core:backspace (input.hidden-input)
     -1:22.6.0 core:move-down (input.hidden-input)
     -1:22.3.0 autocomplete-plus:confirm (input.hidden-input)
     -1:21.5.0 core:move-right (input.hidden-input)
     -1:21.3.0 editor:newline (input.hidden-input)
 21x -1:19.5.0 core:backspace (input.hidden-input)
     -1:09.0 editor:newline (input.hidden-input)
     -1:07.1.0 snippets:next-tab-stop (input.hidden-input)
     -1:07.1.0 snippets:expand (input.hidden-input)
     -1:07.1.0 editor:indent (input.hidden-input)
  2x -1:06.5.0 core:backspace (input.hidden-input)
  3x -1:03.1.0 autocomplete-plus:activate (input.hidden-input)
  7x -0:50.6.0 core:undo (input.hidden-input)
  2x -0:46.9.0 core:backspace (input.hidden-input)
     -0:44.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-moose 0.23.3 
busy-signal 2.0.1 
language-moose 1.3.0 
linter-moose 0.4.0 
moose-doxygen 0.4.0 
switch-header-source 0.34.1 
```

**Comment by dschwen** [comment]
Thanks Marina, I'll look into it.

**Comment by dschwen** [comment]
Is this still an issue? I cannot reproduce it.

**Comment by marinasessim** [comment]
No, this is not an issue anymore. Thanks for your attention!
